### ISSUE TITLE
Failure in extract_lambda_source() with tuple unpacking in lambdas

### ISSUE THREAD

**Issue by tkunisky** [DRMacIver/hypothesis#110]
The following code:

```python
from hypothesis import strategies as st
st.tuples(st.just('a'), st.just('b')).map(lambda (a, b): a + b)
```

fails with this error:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/hypothesis/searchstrategy/strategies.py", line 530, in __repr__
    self.pack)
  File "/usr/local/lib/python2.7/dist-packages/hypothesis/internal/reflection.py", line 265, in get_pretty_function_description
    result = extract_lambda_source(f)
  File "/usr/local/lib/python2.7/dist-packages/hypothesis/internal/reflection.py", line 208, in extract_lambda_source
    if_confused = 'lambda %s: <unknown>' % (', '.join(args),)
TypeError: sequence item 0: expected string or Unicode, list found
```

As far as I can tell, the problem is that the 'args' field of the argspec is not always a list of strings; in particular, when tuple unpacking is used like this, it can be a nested list of lists. Calling join with such an object then gives the error above.

**Comment by DRMacIver** [comment]
Oh right. Yes, I forgot those were a thing because I write everything in the python 2 / 3 compatible subset of the language (they're not a thing in python 3). Sorry about that. Should be an easy fix I think.

**Comment by DRMacIver** [comment]
Whoops, sorry, this was fixed and shipped a while ago (I'm not sure exactly when) but I forgot to close the bug.
