### ISSUE TITLE
ImportError: No module named faker

### ISSUE THREAD

**Issue by kkurzhal** [DRMacIver/hypothesis#146]
I attempted to import the models module for django and received the specified error in version 1.11.0.  Here is the traceback after running `python manage.py test`:

Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_manager(settings)
  File "/usr/lib/python2.6/site-packages/Django-1.4.10-py2.6.egg/django/core/management/__init__.py", line 459, in execute_manager
    utility.execute()
  File "/usr/lib/python2.6/site-packages/Django-1.4.10-py2.6.egg/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.6/site-packages/Django-1.4.10-py2.6.egg/django/core/management/commands/test.py", line 49, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/usr/lib/python2.6/site-packages/Django-1.4.10-py2.6.egg/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/lib/python2.6/site-packages/Django-1.4.10-py2.6.egg/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.6/site-packages/South-1.0.2-py2.6.egg/south/management/commands/test.py", line 8, in handle
    super(Command, self).handle(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/Django-1.4.10-py2.6.egg/django/core/management/commands/test.py", line 72, in handle
    failures = test_runner.run_tests(test_labels)
  File "/usr/lib/python2.6/site-packages/Django-1.4.10-py2.6.egg/django/test/simple.py", line 380, in run_tests
    suite = self.build_suite(test_labels, extra_tests)
  File "/usr/lib/python2.6/site-packages/Django-1.4.10-py2.6.egg/django/test/simple.py", line 267, in build_suite
    suite.addTest(build_suite(app))
  File "/usr/lib/python2.6/site-packages/Django-1.4.10-py2.6.egg/django/test/simple.py", line 79, in build_suite
    test_module = get_tests(app_module)
  File "/usr/lib/python2.6/site-packages/Django-1.4.10-py2.6.egg/django/test/simple.py", line 36, in get_tests
    test_module = import_module('.'.join(prefix + [TEST_MODULE]))
  File "/usr/lib/python2.6/site-packages/Django-1.4.10-py2.6.egg/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/usr/django-apps/charitytracker/hmis/tests.py", line 3, in <module>
    from hypothesis.extra.django import models
  File "/usr/lib/python2.6/site-packages/hypothesis/extra/django/models.py", line 21, in <module>
    import hypothesis.extra.fakefactory as ff
  File "/usr/lib/python2.6/site-packages/hypothesis/extra/fakefactory.py", line 21, in <module>
    import faker
ImportError: No module named faker

**Comment by DRMacIver** [comment]
You need fake-factory installed for the django support. If you want to install Hypothesis with the necessary additional dependencies you can use 'pip install hypothesis[django]', or you can manage their install manually.

**Comment by kkurzhal** [comment]
Thanks!
